name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

# TODO: Add Notion CMS to this workflow

# TODO: Convert to a Docker container

jobs:
  # # Build job - Might not need this with the recent update to https://github.com/marketplace/actions/hugo-setup
  # build:
  #   runs-on: ubuntu-22.04
  #   env:
  #     HUGO_VERSION: 0.106.0
  #   steps:
  #     - name: Install Hugo CLI
  #       run: |
  #         wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb \
  #         && sudo dpkg -i ${{ runner.temp }}/hugo.deb
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         submodules: recursive
  #     - name: Setup Pages
  #       id: pages
  #       uses: actions/configure-pages@v2
  #     - name: Build with Hugo
  #       env:
  #         # For maximum backward compatibility with Hugo modules
  #         HUGO_ENVIRONMENT: production
  #         HUGO_ENV: production
  #       run: |
  #         hugo \
  #           --minify \
  #           --baseURL "${{ steps.pages.outputs.base_url }}/"
  #     - name: Upload artifact
  #       uses: actions/upload-pages-artifact@v1
  #       with:
  #         path: ./public

  # Deployment job
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest' # or 0.106.0
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          exclude_assets: '.github,**/.gitignore'
          # force_orphan: true
